### ISSUE TITLE
DEPRECATION: Using the '{{#each item in model}}' in Ember 1.13

### ISSUE THREAD

**Issue by broerse** [mharris717/ember-cli-pagination#112]
DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper ('
myapp/templates/components/page-numbers.hbs' @ L13:C4) is deprecated. Please use
 the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.

**Comment by shivanibhanwal** [comment]
Yes fix #114 is really needed now if you upgrade your ember to 2.0.0-beta.4 and ember-cli to 1.13.6. Because it does not show page number if we do not use the new syntax.
![screen shot 2015-08-04 at 8 42 01 pm](https://cloud.githubusercontent.com/assets/1167588/9064266/50d0006a-3ae9-11e5-8000-56f4bcd4f5db.png)
